### ISSUE TITLE
can't depoly to azure

### ISSUE THREAD

**Issue by zmes50416** [sedouard/resume#6]
Hi, It work successfully on my local machine, but when I try to use Continuous Deployment to azure by Github.
But It show the error:
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\Program Files (x86)\nodejs\4.4.7\node.exe" "D:\Program Files (x86)\npm\2.15.8\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\home\site\repository\node_modules\resume-cli\node_modules\resume-schema\node_modules\z-schema\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json.78354339
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename

npm ERR! EINVAL: invalid argument, rename 'D:\home\site\repository\node_modules\resume-cli\node_modules\resume-schema\node_modules\z-schema\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json.78354339' -> 'D:\home\site\repository\node_modules\resume-cli\node_modules\resume-schema\node_modules\z-schema\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\repository\npm-debug.log
Failed exitCode=-4071, command=npm install
`

I find out the problem is on the Window OS that **path is too long and rename argument cant be longer than 255 word**. If I manually change to root directory then It can build without any problem. 
since I am not familiar with azure. Have you encouter the same problem? Or is there anyway I can solve this problem since I don't know how to change the deploy location.

**Comment by sedouard** [comment]
Hey @zmes50416 you'll probably need to upgrade to npm 3. It has the fix for path-too-long errors on windows.

**Comment by zmes50416** [comment]
@sedouard Yes, Change npm to 3.10 and it work great now! THANK YOU VERY MUCH!
