### ISSUE TITLE
BizSpark url is broken

### ISSUE THREAD

**Issue by josemaia** [sedouard/resume#7]
Hello Steven,

The url in the README.MD file at "If you're working on a Startup signup for [Bizspark](url)" is pointing to a relative URL that doesn't exist, instead of the real one.

Cheers,
José Maia.

**Comment by sedouard** [comment]
Thanks! closed via https://github.com/sedouard/resume/commit/3b2a8d453d0fe19e4ef63949921b27d0e25ac8df
